ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.TransferRepetitionTrap]
path = "out/TransferWithExactRepetitionTrap.sol/TransferWithExactRepetitionTrap.json"
response_contract = "0x61C040f01fbb70E6d8e377E13c4C6793835e790e"
response_function = "respondToRepetition(bytes[])"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 3
private_trap = true
whitelist = []
